import {
  newQuoteId,
  newRouteId,
  type PaymentIntent,
  type PaymentRail,
  type Quote,
  type RailKind,
  type Transfer,
  type TransferStatus,
} from "@mova/domain";

/**
 * Illustrative NGN/local -> destination FX ratios, keyed "SRC:DST".
 * These are NOT market data — see docs/security.md's "never fabricate a
 * capability" principle. They exist only so mock quotes are internally
 * consistent (a bigger source amount produces a proportionally bigger
 * destination amount) for demo purposes. Unknown pairs fall back to a
 * transparent 1:1 ratio rather than a fabricated-looking cross rate.
 */
const ILLUSTRATIVE_RATES: Record<string, number> = {
  "NGN:BOB": 0.0133,
  "NGN:USD": 0.00065,
  "NGN:USDC": 0.00065,
  "USD:BOB": 12.5,
  "USDC:BOB": 12.5,
};

function illustrativeRate(sourceCurrency: string, destCurrency: string): number {
  if (sourceCurrency === destCurrency) return 1;
  const direct = ILLUSTRATIVE_RATES[`${sourceCurrency}:${destCurrency}`];
  if (direct !== undefined) return direct;
  const inverse = ILLUSTRATIVE_RATES[`${destCurrency}:${sourceCurrency}`];
  if (inverse !== undefined) return 1 / inverse;
  return 1;
}

function randomInRange(min: number, max: number): number {
  return min + Math.random() * (max - min);
}

/** Mock arithmetic only: real money handling in MOVA stays decimal-string
 * end to end (see packages/domain/src/money.ts). Floats here are fine
 * because this class never produces a real settlement number, only an
 * illustrative one, and the result is immediately re-serialized to a
 * fixed-precision decimal string. */
function toFixedAmount(n: number): string {
  return Math.max(0, n).toFixed(2);
}

type TransferRecord = {
  transfer: Transfer;
  createdAtMs: number;
  estimatedDurationMs: number;
};

/** Fraction of the quoted ETA that must elapse before a PENDING transfer
 * is reported as PROCESSING. Tuned for demo pacing, not measured from any
 * real settlement pipeline. */
const PROCESSING_START_RATIO = 0.2;

/**
 * MOCK bank-transfer rail modeling Nigerian NIP-style bank-to-bank
 * transfer characteristics: higher reliability, moderate latency, and
 * tight fee variance relative to the P2P/agent-network rail.
 *
 * capability: "MOCK" — there is no live connection to any Nigerian bank
 * or NIP switch. A production NigerianBankRail would need a licensed
 * provider relationship and KYC infrastructure that is explicitly out of
 * scope for this hackathon (see docs/african-rails.md). Every fee/ETA/
 * confidence number produced here is generated by a documented formula
 * below, never presented as observed market data.
 */
export class NigerianBankRail implements PaymentRail {
  readonly id = "rail-bank-ngn-mock";
  readonly kind: RailKind = "BANK";
  readonly capability = "MOCK" as const;

  private readonly transfers = new Map<string, TransferRecord>();

  async getQuote(intent: PaymentIntent): Promise<Quote> {
    const parsedSource = Number.parseFloat(intent.source.amount);
    const sourceAmount = Number.isFinite(parsedSource) ? parsedSource : 0;

    // Fee: 1.00%-1.30% of source amount. Chosen so a ~150,000-unit
    // transfer lands near the ~1,842 illustrative example in
    // docs/african-rails.md — a demo tuning constant, not a real bank
    // fee schedule.
    const feeRatio = randomInRange(0.01, 0.013);
    const fee = sourceAmount * feeRatio;

    const rate = illustrativeRate(intent.source.currency, intent.destination.currency);
    let destinationAmount = Math.max(0, sourceAmount - fee) * rate;

    const minimumReceived = intent.destination.minimumReceived
      ? Number.parseFloat(intent.destination.minimumReceived)
      : undefined;
    if (
      minimumReceived !== undefined &&
      Number.isFinite(minimumReceived) &&
      destinationAmount > 0 &&
      destinationAmount < minimumReceived &&
      minimumReceived / destinationAmount <= 1.5
    ) {
      // Nudge up to satisfy the stated minimum when it's in a plausible
      // range for our illustrative rate — we're not modeling real FX,
      // just keeping the quote internally consistent with the intent.
      destinationAmount = minimumReceived * 1.001;
    }

    // ETA: ~4.7-7.7 minutes — moderate latency, the rail's characteristic
    // trait per docs/african-rails.md.
    const estimatedDurationSeconds = Math.round(randomInRange(282, 462));
    // Confidence: 98.5%-99.7% — higher and tighter than the P2P rail,
    // modeling bank-transfer reliability. Illustrative only, not a
    // measured success rate (see docs/african-rails.md "What would break
    // this in production").
    const confidence = randomInRange(0.985, 0.997);

    const now = new Date();
    const expiresAt = new Date(now.getTime() + 90_000); // 90s quote validity

    return {
      id: newQuoteId(),
      intentId: intent.id,
      sourceAmount: sourceAmount.toFixed(2),
      destinationAmount: toFixedAmount(destinationAmount),
      fee: toFixedAmount(fee),
      rate: rate.toFixed(6),
      estimatedDurationSeconds,
      // Placeholder RouteId stamp only. Assembling an actual Route is the
      // routing-engine's job (packages/domain/src/routes/route.ts) — this
      // rail produces Quotes, never Route objects.
      routeId: newRouteId(),
      createdAt: now.toISOString(),
      expiresAt: expiresAt.toISOString(),
      provider: "mock-ngn-bank",
      metadata: {
        capability: "MOCK",
        confidence: Number(confidence.toFixed(4)),
        rail: this.kind,
        sourceCurrency: intent.source.currency,
        destinationCurrency: intent.destination.currency,
        note: "Mock-generated fee/ETA/confidence per docs/african-rails.md; not observed bank data.",
      },
    };
  }

  async createTransfer(intent: PaymentIntent, quote: Quote): Promise<Transfer> {
    const nowIso = new Date().toISOString();
    const transfer: Transfer = {
      id: `trf_${crypto.randomUUID().replace(/-/g, "").slice(0, 20)}`,
      railId: this.id,
      intentId: intent.id,
      quoteId: quote.id,
      status: "PENDING",
      createdAt: nowIso,
      updatedAt: nowIso,
    };
    this.transfers.set(transfer.id, {
      transfer,
      createdAtMs: Date.now(),
      estimatedDurationMs: Math.max(1, quote.estimatedDurationSeconds) * 1000,
    });
    return transfer;
  }

  /**
   * `now` is an optional seam for deterministic tests (see
   * src/index.test.ts) — PaymentRail callers can ignore it entirely and
   * get real time-based progression.
   *
   * Behavior for an unknown id is a thrown Error, not a silent fallback
   * status: a status poll should never lie about a transfer it has no
   * record of.
   */
  async getStatus(id: string, now: number = Date.now()): Promise<TransferStatus> {
    const record = this.transfers.get(id);
    if (!record) {
      throw new Error(`NigerianBankRail: unknown transfer id "${id}"`);
    }
    if (record.transfer.status === "CANCELLED" || record.transfer.status === "FAILED") {
      return record.transfer.status;
    }

    const elapsedMs = now - record.createdAtMs;
    let status: TransferStatus;
    if (elapsedMs >= record.estimatedDurationMs) {
      status = "COMPLETED";
    } else if (elapsedMs >= record.estimatedDurationMs * PROCESSING_START_RATIO) {
      status = "PROCESSING";
    } else {
      status = "PENDING";
    }

    record.transfer.status = status;
    record.transfer.updatedAt = new Date(now).toISOString();
    return status;
  }

  /**
   * Best-effort no-op when the id is unknown (unlike getStatus, which
   * throws) — cancellation is inherently idempotent/fire-and-forget in
   * this mock, per docs/african-rails.md.
   */
  async cancel(id: string, now: number = Date.now()): Promise<void> {
    const record = this.transfers.get(id);
    if (!record) return;
    if (record.transfer.status === "COMPLETED") return;
    record.transfer.status = "CANCELLED";
    record.transfer.updatedAt = new Date(now).toISOString();
  }
}
